### ISSUE TITLE
Any get EXIF from video files?

### ISSUE THREAD

**Issue by patprzybilla** [devongovett/exif-reader#12]
Hi,

great piece of code. Works well with images. however I was looking into getting exif data from video formats. Do you know anything about it? I would love to make that work.

**Comment by lovell** [comment]
If you can extract just the EXIF from the video as an instance of a `Buffer`, then yes, this should work.

Each of the various video container formats usually have their own metadata structure as well as (most) providing support for EXIF/XMP etc. It might be worth experimenting on the sort of video files you'd need to process using command line tools such as `ffmpeg` and `exiftool` first.
