### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by atombrenner** [devongovett/exif-reader#27]
If you use this project with typescript, you have to create a declaration file every time to prevent this error: 

``` text
Could not find a declaration file for module 'exif-reader'. '/home/Code/node_modules/exif-reader/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/exif-reader` if it exists or add a new declaration (.d.ts) file containing `declare module 'exif-reader';`
```

It will be easier to add type definitions directly to this project instead of maintaining a mirror in the  already too large  [DefinetelyTyped (@types)](https://github.com/DefinitelyTyped/DefinitelyTyped#readme) project.

**Comment by lovell** [comment]
> you have to create a declaration file every time

Did you see https://www.npmjs.com/package/@types/exif-reader ?

**Comment by atombrenner** [comment]
Yes. The type definitions from DefinitelyTyped just make the initial error go away, but after that all tags are still of type `unknown`.
IMHO the type definitions and developer experience can be improved by adding more specific type definitions to the package. For example, the tags `DateTimeOriginal`, `DateTimeDigitized` and `ModifyDate` are always of type `Date`.  Packaging has the additional benefit that you don't need to install another dependency, and that the types are in sync with potential implementation changes. 
I can create a PR with my current to demonstrate the improvement.

**Comment by lovell** [comment]
Closing as v2.0.0 moved the TypeScript definitions in-house.
